### ISSUE TITLE
Logging format and level issues

### ISSUE THREAD

**Issue by gonzoinc** [jameswlane/status-board#142]
- `react` version: react@16.2.0 
- `node` version: v9.8.0
- `npm` version: 5.6.0

Relevant code or config

/config/logging.js

```
module.exports = {

  "liveLoggingWebAccess": true, // disabled by default for security reasons

  "morgan": 'common', // settings for express's logging: https://www.npmjs.com/package/morgan

  /**
   * https://www.npmjs.com/package/tracer
   */

  "logger": {

    "format": [
    "{timestamp: '{{timestamp}}', title: '{{title}}', file: '{{file}}', line:'{{line}}', method: '{{method}}', message: '{{message}}' }" ,
      //"{{timestamp}} <{{title}}> {{message}} ({{file}})\nCall Stack:\n{{stack}}",
      {
        // error template
        "error": "{{timestamp}} <{{title}}> {{message}} (in {{file}}:{{line}})\nCall Stack:\n{{stack}}"
      }
    ],
    "dateformat": "HH:MM:ss.L",
    "level": "error"
  }
};

```

What you did:

Updated the format to output a standard JSON format to be used with our ElasticSearch cluster. Set morgan logger to common and tracer level to error.

Problem description:

This is the format that gets output:
 
```
::1 - - [13/Mar/2018:15:39:03 +0000] "GET / HTTP/1.1" 200 -
::1 - - [13/Mar/2018:15:39:04 +0000] "GET /stylesheets/normalize.css HTTP/1.1" 200 -
::1 - - [13/Mar/2018:15:39:04 +0000] "GET /stylesheets/application.css HTTP/1.1" 200 -
::1 - - [13/Mar/2018:15:39:04 +0000] "GET /fonts/roboto-condensed.woff HTTP/1.1" 200 17304
::1 - - [13/Mar/2018:15:39:08 +0000] "GET /Engineering HTTP/1.1" 200 -
 
```

It is not using the format options in any way shape or form. This is just the standard morgan predefined format.  It is also not abiding by any log level that is set for it. I have tried numerical and method name.  It seems to be stuck in "log" level which is spamming our logs with the "executed Ok" messages. For the time being I'm having to comment out that line in Scheduler.js each time we deploy to stop the log spam.

**Comment by jameswlane** [comment]
@gonzoinc I disabled a lot of the logging for the time being while I work through testing all the code [See issue](https://github.com/jameswlane/status-board/issues/44), Once that's done I will work on adding it back in. I took vacation this week to try and finish all the test and get the logger back to working.

Also I created a [slack](https://slackin-xmjstmxrio.now.sh/) if you wanted to join

**Comment by jameswlane** [comment]
@gonzoinc I am while working on the test for the logger this week I should also get it working again. I am starting that work today.

**Comment by jameswlane** [comment]
@gonzoinc This should be working again.

We disabled the logger when we started due to it wouldn't compile in TypeScript. Did alot of digging and found out it was due to a circle dependencies in the logger and config manager that was causing compile issues. I have finally resolved it and re-implemented it back in the application. Let if you have any other issues.

**Comment by jameswlane** [comment]
@gonzoinc - I am working on a new release that will allow you to have jobs/widgets as a package, I am wondering what version of Node do you use for Status Board?

**Comment by gonzoinc** [comment]
@jameswlane currently running v9.7.1

**Comment by jameswlane** [comment]
@gonzoinc Awesome, I am looking at the 2.0.0 release to be `async` / `await` so that would mean Node 8 or higher.
