### ISSUE TITLE
Dashboard Pages

### ISSUE THREAD

**Issue by elibosley** [jameswlane/status-board#285]
HI!

My company has been using Atlasboard for a while time and are thinking about migrating to your version of the project. We currently have a lot of our own custom code that is used to group widgets into categories by folders 
If we were to switch, would you be open to accepting pull requests adding additional functionality to areas like this? We wanted to make sure before migrating but really like updates. 

Thanks

**Comment by jameswlane** [comment]
@elibosley 
Pull request are always welcome, and I am open to adding new functionality.
I am working on a list of items / functionality / improvements I plan for Status Board over the next year.
I would love to hear any and all feedback to help prioritize the list.

If you guys have any questions or run into issues, let me know I am generally very good at replying within twenty four hours or less.

**Comment by jameswlane** [comment]
@elibosley Was I able to answer your question?

If so can I close this issue?

**Comment by elibosley** [comment]
Yes - please close it, I'm working on adapting your framework and very
excited about it :)

**Comment by jameswlane** [comment]
@elibosley  - I am working on a new release, what version of Node do you use for Status Board?
