### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by poznachowski** [jameswlane/status-board#292]
Hello, 

I once prepared an Atlasboard dashboard despite not having much experience with Node. I would like to use Statusboard now, and it's confusing to me how should I get started (from scratch). Could you provide some more info ?

**Comment by jameswlane** [comment]
@poznachowski Sure, I would love to.

Do you use the Atlasboard CLI to start your instance or directly from the project?

**Comment by poznachowski** [comment]
I did not use Atlasboard CLI. I find confusing how Statusboard relates to Atlasboard. Should I first generate dashboard using Atlasboard and then run statusboard against generated code?

**Comment by jameswlane** [comment]
Pretty much, it should just drop in and replace Atlasboard. I am working on releasing a new CLI for Status Board. Should be done with it by end of year.

**Comment by poznachowski** [comment]
Got it working, but started to think - what is the current benefit of using statusboard? Dependencies updates?

**Comment by jameswlane** [comment]
Dependencies updates is one, there has been some bug fixes and improvement in code. After talking with some people who worked on Atlasboard, I was told the project is pretty much discontinued. I have a roadmap of new features planned in 2019. I just want to finish up the CLI replacement before getting started.

**Comment by jameswlane** [comment]
@poznachowski, did I answer all your questions? Am I able to close this issue?

**Comment by jameswlane** [comment]
@poznachowski - I am working on a new release, what version of Node do you use for Status Board?
