### ISSUE TITLE
How to install status-board

### ISSUE THREAD

**Issue by Frogli** [jameswlane/status-board#306]
- `status-board` version: 1.1.45
- `node` version: v10.14.2
- `npm` (or `yarn`) version: 6.5.0
- MacOS 10.14.1
- Shell: zsh

Relevant code or config
...
What you did:
I tried to install status-board after I installed atlasboard. What I did was:
1. npm install -g atlasboard
2. Went to the folder where I want to add a wallboard
3. npm install status-board
4. Run ```atlasboard new DevWallBoard
5. Added the dependency ```"status-board": "^1.1.45"``` to the package.json of the wallboard.
6. Checked the start.js, but that seems to be still the atlas-board one.

Now the examples are working, but I am not sure it actually uses status-board. How can I check this?

What happened:
...

Reproduction repository:
....

Problem description:
I did not wanted to hijack the thread https://github.com/jameswlane/status-board/issues/292. It looks a bit like my problem. How do I check that status-board is used and not atlas-board.  

The reason I try status-board is that is looks more current then atlasboard and I have some troubles to get the widget https://github.com/SonarQubeCommunity/atlasboard-sonarqube-package working and saw your call for feedback on status-board.

Suggested solution:
....

**Comment by jameswlane** [comment]
Hello @Frogli,
To use `status-board` here are the steps you should have to take:
* [ ] Remove `atlasboard` from your `package.json`
* [ ] Run `npm i --save status-board`
* [ ] Edit the `start.js` file in your project (See below)

```
"use strict";
var statusBoard = require('status-board').default;

function callback(err) {
  if (err) {
    throw err;
  }
}

statusBoard(options, callback);
```

To verify if you check your`node_modules` folder, `status-board` should be in there and `atlasboard` should be gone.

Let me know if that gets you running if you have any more issue feel free to let me know. I am always happy to help and improve `status-board` as a whole.

**Comment by Frogli** [comment]
Thanks, I got it working!

**Comment by jameswlane** [comment]
@Frogli If you need anything else let me know.

**Comment by jameswlane** [comment]
@Frogli  - I am working on a new release that will allow you to have jobs/widgets as a package, would you be interested in beta testing it?
