### ISSUE TITLE
Need help with some compile errors

### ISSUE THREAD

**Issue by jameswlane** [jameswlane/status-board#42]
@SwamiKalagiri I worked through couple hundred compile errors, I have these left and I have yet figured out a solution. If you have sometime I could use a second pair of eyes on these, maybe I am missing something.
- [ ] Error TS2304: Cannot find name 'MediaQueryList'.
`node_modules/@types/stylus/index.d.ts`(1193,26)
Line: 1193 `merge(other: MediaQueryList): MediaQueryList;`

- [ ] Error TS2304: Cannot find name 'MediaQueryList'.
`node_modules/@types/stylus/index.d.ts`(1193,43)
Line: 1193 `merge(other: MediaQueryList): MediaQueryList;`

- [ ] Error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'. Type 'undefined' is not assignable to type 'string'.
`src/config-manager.ts`(32,38)
Line: 32 `const configValue = JSON.parse(process.env[key]);`

- [ ] Error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'. Type 'undefined' is not assignable to type 'string'.
`src/config-manager.ts`(35,27)
Line: 35 `return JSON.parse(process.env[key]);`

- [ ] Error TS2425: Class 'StorageBase' defines instance member property 'get', but extended class 'StorageFS' defines it as instance member function.
`src/job-dependencies/storage/implementations/StorageFS.ts`(21,10)
Line: 21 `public get(key: any, callback: any) {`

- [ ] Error TS2425: Class 'StorageBase' defines instance member property 'set', but extended class 'StorageFS' defines it as instance member function.
`src/job-dependencies/storage/implementations/StorageFS.ts`(39,10)
Line: 39 `public set(key: any, value: any, callback: any) {`

- [ ] Error TS2425: Class 'StorageBase' defines instance member property 'get', but extended class 'StorageRedis' defines it as instance member function.
`src/job-dependencies/storage/implementations/StorageRedis.ts`(16,10)
Line: 16 `public get() {`

- [ ] Error TS2425: Class 'StorageBase' defines instance member property 'set', but extended class 'StorageRedis' defines it as instance member function.
`src/job-dependencies/storage/implementations/StorageRedis.ts`(20,10)
Line: 20 `public set() {`

- [ ] Error TS2345: Argument of type '({} | undefined)[] | undefined' is not assignable to parameter of type 'List<any>'. Type 'undefined' is not assignable to type 'List<any>'.
`src/package-dependency-manager.ts`(119,29)
Line: 119 `const paths = _.flatten(results);`

- [ ] Error TS2532: Object is possibly 'undefined'.
`src/webapp/routes/widget.ts`(43,25)
Line: 43 `namespaceRulesAST(cssAST.stylesheet.rules, widgetNamespace);`

**Comment by SwamiKalagiri** [comment]
We still have this compilation errors,

 Error TS2304: Cannot find name 'MediaQueryList'.
node_modules/@types/stylus/index.d.ts(1193,26)
Line: 1193 merge(other: MediaQueryList): MediaQueryList;

 Error TS2304: Cannot find name 'MediaQueryList'.
node_modules/@types/stylus/index.d.ts(1193,43)
Line: 1193 merge(other: MediaQueryList): MediaQueryList;

**Comment by jameswlane** [comment]
Yeah I was looking into it. I am trying to figure out if the types are bad from @types or we are using Stylus wrong.

**Comment by SwamiKalagiri** [comment]
It seems we need to include `dom` libs .  I added `dom` option lib got resolved the issue. Review [commit](https://github.com/jameswlane/status-board/commit/3730c8265ca2bc02f21db3b190bb344d6f9bf8fb)

**Comment by jameswlane** [comment]
Nice, hit the “That was easy” button.
