### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by gonzoinc** [jameswlane/status-board#99]
I seem to not be able to get Environment Variables working with the globalAuth file. Documentation shows the format should be something like the below:

`{
    "JIRA":{
        "username":"${JIRA_USERNAME}",
        "password":"${JIRA_PASSWORD}"
        }
}`

Testing locally with the data set in both .bashrc and .profile when I go to start the application just hangs with no errors. Verified they are set in the environment so it looks like the application is hanging. 

I've tried defining them directly as "process.env.JIRA_USERNAME" in the auth file and removing the link to the globalAuth but it looks like something else is still pointing the widgets to the globalAuth. Only way I can get the application to start again is removing the env variable reference from the globalAuth, and even though I have the authenticationFilePath removed in the auth file I still get this error:

> executed with errors: no credentials found in blockers job. Please check global authentication file (usually config.globalAuth)

And Ideas as to what I can do to remedy this as this is pretty critical due to our environment handling these types of credentials.

Thanks

**Comment by jameswlane** [comment]
I will dig into this tonight, see what I can come up with.

**Comment by jameswlane** [comment]
@gonzoinc I think I have fixed the bug causing the issue you are seeing.
There was a endless loop that I think was causing the issue.
I was able to reproduce it locally and fixed it on a local installation. 
Could you pull down the latest version (v1.1.24) and see if the problem still exists.

**Comment by gonzoinc** [comment]
That did the trick except for it's printing out the actual Env Variables in the output when I start it which I removed in the below.

`> node start

Local Status Board


-------------------------------------------
Atlasboard listening at port 3000
-------------------------------------------


loadGlobalAuth { JIRA: { username: '*******', password: '********' } }`

**Comment by jameswlane** [comment]
I can look at that this evening and remove the print out, to make it more secure.

**Comment by jameswlane** [comment]
I found a left over `console.log` I removed it. The issue should be resolved in version v1.1.25
